In [1]:
import numpy as np 
import pandas as pd

In [4]:
#creating dataframe
data={
    'Name':['Kshitij','John','Jack'],
    'Age':[22,30,45],
    'City':['Bangalore','New York','Florida'],
    'Salary':[65000,70000,62000]
}

df=pd.DataFrame(data)
df

      Name  Age       City  Salary
0  Kshitij   22  Bangalore   65000
1     John   30   New York   70000
2     Jack   45    Florida   62000

In [19]:
data_list=[
    ['John',28,'New York',65000], 
    ['Peter Pan',29,'Berlin', 62000], 
    ['Linda', 42 ,'London',85000]
]
df2=pd.DataFrame(data_list)
df2

           0   1         2      3
0       John  28  New York  65000
1  Peter Pan  29    Berlin  62000
2      Linda  42    London  85000

In [37]:
col=["Name","Age","City","Salary"]
df2=pd.DataFrame(data_list,columns=col)
df2

        Name  Age      City  Salary
0       John   28  New York   65000
1  Peter Pan   29    Berlin   62000
2      Linda   42    London   85000

Selection and indexing of columns

In [38]:
df2["Name"]

0         John
1    Peter Pan
2        Linda
Name: Name, dtype: object

In [39]:
df2[["Name","City"]]

        Name      City
0       John  New York
1  Peter Pan    Berlin
2      Linda    London

Creating new column

In [40]:
df2["Designation"]=["Doc","Eng.","Doc"]
df2

        Name  Age      City  Salary Designation
0       John   28  New York   65000         Doc
1  Peter Pan   29    Berlin   62000        Eng.
2      Linda   42    London   85000         Doc

Removing Column

In [41]:
df2.drop("Designation")

KeyError: "['Designation'] not found in axis"

In [ ]:
df2.drop("Designation",axis=1)

In [42]:
df2

        Name  Age      City  Salary Designation
0       John   28  New York   65000         Doc
1  Peter Pan   29    Berlin   62000        Eng.
2      Linda   42    London   85000         Doc

In [43]:
df2.drop("Designation",axis=1,inplace=True)
df2

        Name  Age      City  Salary
0       John   28  New York   65000
1  Peter Pan   29    Berlin   62000
2      Linda   42    London   85000

selecting rows

In [44]:
df2.loc[0]

Name          John
Age             28
City      New York
Salary       65000
Name: 0, dtype: object

In [45]:
df2.loc[[0,2]]

    Name  Age      City  Salary
0   John   28  New York   65000
2  Linda   42    London   85000

In [46]:
df2.iloc[2]

Name       Linda
Age           42
City      London
Salary     85000
Name: 2, dtype: object

select subset of rows and columns

In [47]:
df2.loc[[0,1]]

        Name  Age      City  Salary
0       John   28  New York   65000
1  Peter Pan   29    Berlin   62000

In [49]:
df2.loc[[0,1]][["City","Salary"]]

       City  Salary
0  New York   65000
1    Berlin   62000

Conditional selection

In [50]:
#age>30 
df2["Age"]>30

0    False
1    False
2     True
Name: Age, dtype: bool

In [51]:
df2[df2["Age"]>30]

    Name  Age    City  Salary
2  Linda   42  London   85000

In [56]:
#age>25 and city=londom

df2[(df2["Age"]>25) & (df2["City"]=="London")]

    Name  Age    City  Salary
2  Linda   42  London   85000