In [1]:
import numpy as np 
import pandas as pd

GroupBy

In [2]:
data = {
    'Category': ['A', 'B', 'A', 'B', 'A', 'B', 'A', 'B'],
    'Store': ['S1', 'S1', 'S2', 'S2', 'S1', 'S2', 'S2', 'S1'],
    'Sales': [100, 200, 150, 250, 120, 180, 200, 300],
    'Quantity': [10, 15, 12, 18, 8, 20, 15, 25],
    'Date': pd.date_range('2023-01-01', periods=8)
}
df = pd.DataFrame(data)

In [3]:
df

  Category Store  Sales  Quantity       Date
0        A    S1    100        10 2023-01-01
1        B    S1    200        15 2023-01-02
2        A    S2    150        12 2023-01-03
3        B    S2    250        18 2023-01-04
4        A    S1    120         8 2023-01-05
5        B    S2    180        20 2023-01-06
6        A    S2    200        15 2023-01-07
7        B    S1    300        25 2023-01-08

In [6]:
# Group by Category and calculate the sum of Sales
df.groupby("Category").sum("Sales")

          Sales  Quantity
Category
A           570        45
B           930        78

In [7]:
df.groupby('Category')['Sales'].sum()

Category
A    570
B    930
Name: Sales, dtype: int64

In [3]:
df=pd.read_csv("weather_by_cities.csv")
df

         day      city  temperature  windspeed   event
0   1/1/2017  new york           32          6    Rain
1   1/2/2017  new york           36          7   Sunny
2   1/3/2017  new york           28         12    Snow
3   1/4/2017  new york           33          7   Sunny
4   1/1/2017    mumbai           90          5   Sunny
5   1/2/2017    mumbai           85         12     Fog
6   1/3/2017    mumbai           87         15     Fog
7   1/4/2017    mumbai           92          5    Rain
8   1/1/2017     paris           45         20   Sunny
9   1/2/2017     paris           50         13  Cloudy
10  1/3/2017     paris           54          8  Cloudy
11  1/4/2017     paris           42         10  Cloudy

In [5]:
g=df.groupby('city')
g

In [8]:
for city,data in g:
    print(f"City : {city}")
    #print("\n")
    print("max : ", data.temperature.max())

City : mumbai
max :  92
City : new york
max :  36
City : paris
max :  54

In [15]:
df.groupby('city').max()

               day  temperature  windspeed  event
city
mumbai    1/4/2017           92         15  Sunny
new york  1/4/2017           36         12  Sunny
paris     1/4/2017           54         20  Sunny

In [17]:
df.groupby('city')["temperature"].max()

city
mumbai      92
new york    36
paris       54
Name: temperature, dtype: int64

In [18]:
g.size()

city
mumbai      4
new york    4
paris       4
dtype: int64

In [19]:
  g.count()

          day  temperature  windspeed  event
city
mumbai      4            4          4      4
new york    4            4          4      4
paris       4            4          4      4

<h4>Group data using custom function: Let's say you want to group your data using custom function. Here the requirement is to create three groups<h4>
<ol>
    <li>Days when temperature was between 80 and 90</li>
    <li>Days when it was between 50 and 60</li>
    <li>Days when it was anything else</li>
</ol>