In [1]:
import numpy as np 
import pandas as pd

In [2]:
data = {
    'Date': pd.date_range('2023-01-01', periods=20),
    'Product': ['A', 'B', 'C', 'D'] * 5,
    'Region': ['East', 'West', 'North', 'South', 'East', 'West', 'North', 'South', 'East', 'West',
               'North', 'South', 'East', 'West', 'North', 'South', 'East', 'West', 'North', 'South'],
    'Sales': np.random.randint(100, 1000, 20),
    'Units': np.random.randint(10, 100, 20),
    'Rep': ['John', 'Mary', 'Bob', 'Alice', 'John', 'Mary', 'Bob', 'Alice', 'John', 'Mary',
            'Bob', 'Alice', 'John', 'Mary', 'Bob', 'Alice', 'John', 'Mary', 'Bob', 'Alice']
}

df = pd.DataFrame(data)

df['Month'] = df['Date'].dt.month_name()
df['Quarter'] = 'Q' + df['Date'].dt.quarter.astype(str)
df

         Date Product Region  Sales  Units    Rep    Month Quarter
0  2023-01-01       A   East    588     91   John  January      Q1
1  2023-01-02       B   West    530     53   Mary  January      Q1
2  2023-01-03       C  North    240     49    Bob  January      Q1
3  2023-01-04       D  South    769     66  Alice  January      Q1
4  2023-01-05       A   East    562     83   John  January      Q1
5  2023-01-06       B   West    729     95   Mary  January      Q1
6  2023-01-07       C  North    170     38    Bob  January      Q1
7  2023-01-08       D  South    387     89  Alice  January      Q1
8  2023-01-09       A   East    978     83   John  January      Q1
9  2023-01-10       B   West    706     91   Mary  January      Q1
10 2023-01-11       C  North    229     28    Bob  January      Q1
11 2023-01-12       D  South    656     46  Alice  January      Q1
12 2023-01-13       A   East    915     70   John  January      Q1
13 2023-01-14       B   West    426     36   Mary  January      Q1
14 2023-01-15       C  North    819     23    Bob  January      Q1
15 2023-01-16       D  South    575     43  Alice  January      Q1
16 2023-01-17       A   East    870     91   John  January      Q1
17 2023-01-18       B   West    882     19   Mary  January      Q1
18 2023-01-19       C  North    593     81    Bob  January      Q1
19 2023-01-20       D  South    311     12  Alice  January      Q1

In [7]:
gr=df.groupby("Product")
gr

In [8]:
for i,v in gr:
    print(i)
    print(v)

A
         Date Product Region  Sales  Units   Rep    Month Quarter
0  2023-01-01       A   East    588     91  John  January      Q1
4  2023-01-05       A   East    562     83  John  January      Q1
8  2023-01-09       A   East    978     83  John  January      Q1
12 2023-01-13       A   East    915     70  John  January      Q1
16 2023-01-17       A   East    870     91  John  January      Q1
B
         Date Product Region  Sales  Units   Rep    Month Quarter
1  2023-01-02       B   West    530     53  Mary  January      Q1
5  2023-01-06       B   West    729     95  Mary  January      Q1
9  2023-01-10       B   West    706     91  Mary  January      Q1
13 2023-01-14       B   West    426     36  Mary  January      Q1
17 2023-01-18       B   West    882     19  Mary  January      Q1
C
         Date Product Region  Sales  Units  Rep    Month Quarter
2  2023-01-03       C  North    240     49  Bob  January      Q1
6  2023-01-07       C  North    170     38  Bob  January      Q1
10 2023-01-11       C  North    229     28  Bob  January      Q1
14 2023-01-15       C  North    819     23  Bob  January      Q1
18 2023-01-19       C  North    593     81  Bob  January      Q1
D
         Date Product Region  Sales  Units    Rep    Month Quarter
3  2023-01-04       D  South    769     66  Alice  January      Q1
7  2023-01-08       D  South    387     89  Alice  January      Q1
11 2023-01-12       D  South    656     46  Alice  January      Q1
15 2023-01-16       D  South    575     43  Alice  January      Q1
19 2023-01-20       D  South    311     12  Alice  January      Q1

In [9]:
pd.pivot_table(df,values="Sales",index='Region',columns="Product")

Product      A      B      C      D
Region
East     782.6    NaN    NaN    NaN
North      NaN    NaN  410.2    NaN
South      NaN    NaN    NaN  539.6
West       NaN  654.6    NaN    NaN

In [10]:
pd.pivot_table(df,values="Sales",index='Region',columns="Product",aggfunc='median')

Product      A      B      C      D
Region
East     870.0    NaN    NaN    NaN
North      NaN    NaN  240.0    NaN
South      NaN    NaN    NaN  575.0
West       NaN  706.0    NaN    NaN

In [12]:
#pivot table with multiple values
pivot2=pd.pivot_table(df,values=['Sales','Units'],index='Region',columns="Product")
pivot2

         Sales                      Units
Product      A      B      C      D     A     B     C     D
Region
East     782.6    NaN    NaN    NaN  83.6   NaN   NaN   NaN
North      NaN    NaN  410.2    NaN   NaN   NaN  43.8   NaN
South      NaN    NaN    NaN  539.6   NaN   NaN   NaN  51.2
West       NaN  654.6    NaN    NaN   NaN  58.8   NaN   NaN

Cross tabs

In [13]:
pd.crosstab(df['Region'],df['Product'])

Product  A  B  C  D
Region
East     5  0  0  0
North    0  0  5  0
South    0  0  0  5
West     0  5  0  0